# Generated by Django 4.0.6 on 2022-07-21 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_restaurant_latitude_alter_restaurant_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='category',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='category_food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catogory_food', to='restaurants.category'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='category_region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catogory_region', to='restaurants.category'),
        ),
    ]
